### ISSUE TITLE
[read blob] need somebody to help

### ISSUE THREAD

**Issue by parkma99** [codecrafters-io/git-starter-rust#15]
Today I try to work this challenge, but got ` [stage-2] Expected "dooby dooby dumpty dumpty scooby yikes" as stdout, got: "blob 38\x00dooby dooby dumpty dumpty scooby yikes"`.
Could you someboy help me

**Comment by rohitpaulk** [comment]
Hey @parkma99! 

Mind hopping in [our Discord](https://discord.com/invite/DeqUD2P) and asking this in the #debugging-help-git channel? That's the best place to get help 🙂 GitHub issues are to report issues with the starter code. 

Also, in case it helps, there are some published solutions on GitHub that you can look at for reference: https://github.com/search?q=codecrafters+git+rust.

**Comment by parkma99** [comment]
Thank you for your help.I find what i do wrong.
